language: node_js
node_js:
  - "6"
install:
  - npm install -g mocha
  - npm --prefix ./hubot/modules/proto-helper install ./hubot/modules/proto-helper
  - npm --prefix ./hubot/modules/config-helper install ./hubot/modules/config-helper
script:
  - (cd ./hubot/modules/proto-helper && mocha)
  - (cd ./hubot/modules/config-helper && mocha)
